#include <initializer_list>
#include <string>

inline std::initializer_list<const std::string> midiCcNames =
{
    "Bank Select (MSB)",
    "Modulation Wheel (MSB)",
    "Breath Controller (MSB)",
    "Undefined 3",
    "Foot Pedal (MSB)",
    "Portamento Time (MSB)",
    "Data Entry MSB",
    "Channel Volume (MSB)",
    "Balance (MSB)",
    "Undefined 9",
    "Pan Position (MSB)",
    "Expression (MSB)",
    "Effect Control 1 (MSB)",
    "Effect Control 2 (MSB)",
    "Undefined 14",
    "Undefined 15",
    "General Purpose Slider 1",
    "General Purpose Slider 2",
    "General Purpose Slider 3",
    "General Purpose Slider 4",
    "Undefined 20",
    "Undefined 21",
    "Undefined 22",
    "Undefined 23",
    "Undefined 24",
    "Undefined 25",
    "Undefined 26",
    "Undefined 27",
    "Undefined 28",
    "Undefined 29",
    "Undefined 30",
    "Undefined 31",
    "Bank Select (LSB)",
    "Modulation Wheel (LSB)",
    "Breath Controller (LSB)",
    "Undefined 35",
    "Foot Pedal (LSB)",
    "Portamento/Glide Time (LSB)",
    "Data Entry (LSB)",
    "Volume (LSB)",
    "Balance (LSB)",
    "Undefined 41",
    "Pan Position (LSB)",
    "Expression (LSB)",
    "Effect Control 1 (LSB)",
    "Effect Control 2 (LSB)",
    "Undefined 46",
    "Undefined 47",
    "Undefined 48",
    "Undefined 49",
    "Undefined 50",
    "Undefined 51",
    "Undefined 52",
    "Undefined 53",
    "Undefined 54",
    "Undefined 55",
    "Undefined 56",
    "Undefined 57",
    "Undefined 58",
    "Undefined 59",
    "Undefined 60",
    "Undefined 61",
    "Undefined 62",
    "Undefined 63",
    "Sustain Pedal On/Off",
    "Portamento/Glide On/Off",
    "Sostenuto On/Off",
    "Soft Pedal On/Off",
    "Legato On/Off",
    "Hold Pedal 2",
    "Sound Variation",
    "Resonance (Timbre)",
    "Sound Release Time",
    "Sound Attack Time",
    "Frequency Cutoff",
    "Sound Controller 6",
    "Sound Controller 7",
    "Sound Controller 8",
    "Sound Controller 9",
    "Sound Controller 10",
    "General Purpose",
    "General Purpose",
    "General Purpose",
    "General Purpose",
    "Undefined 84",
    "Undefined 85",
    "Undefined 86",
    "Undefined 87",
    "Undefined 88",
    "Undefined 89",
    "Undefined 90",
    "Effect 1 Amount (Reverb)",
    "Effect 2 Amount (Tremolo)",
    "Effect 3 Amount (Chorus)",
    "Effect 4 Amount (Detuning)",
    "Effect 5 Amount (Phaser)",
    "Data Bound Increment (+1)",
    "Data Bound Decrement (-1)",
    "NRPN LSB",
    "NRPN MSB",
    "RPN LSB",
    "RPN MSB",
    "Undefined 102",
    "Undefined 103",
    "Undefined 104",
    "Undefined 105",
    "Undefined 106",
    "Undefined 107",
    "Undefined 108",
    "Undefined 109",
    "Undefined 110",
    "Undefined 111",
    "Undefined 112",
    "Undefined 113",
    "Undefined 114",
    "Undefined 115",
    "Undefined 116",
    "Undefined 117",
    "Undefined 118",
    "Undefined 119",
    "Channel Mute / Sound Off",
    "Reset All Controllers",
    "Local Keyboard On/Off Switch",
    "All MIDI Notes OFF",
    "OMNI Mode OFF",
    "OMNI Mode ON",
    "Mono Mode",
    "Poly Mode",
    "Off"
};