#ifndef PORTS_HPP_
#define PORTS_HPP_

// Plugin ports as declared in the .ttl file
enum BVibratrPorts
{
	BVIBRATR_MIDI_IN			= 0,
	BVIBRATR_AUDIO_IN_1			= 1,
	BVIBRATR_AUDIO_IN_2			= 2,
	BVIBRATR_AUDIO_OUT_1		= 3,
	BVIBRATR_AUDIO_OUT_2		= 4,
	BVIBRATR_NR_PORTS			= 5
	
};

// Plugin control ports as declared in the .ttl file, offset to
// BVibratrPorts::BVIBRATR_PORTS
enum BVibratrControllers
{
	BVIBRATR_BYPASS				= 0,
	BVIBRATR_DRY_WET			= 1,
	BVIBRATR_MIDI_CHANNEL		= 2,
	BVIBRATR_MIDI_NOTE			= 3,
	BVIBRATR_DEPTH_IS_CC		= 4,
	BVIBRATR_DEPTH				= 5,
	BVIBRATR_DEPTH_ATTACK		= 6,
	BVIBRATR_DEPTH_DECAY		= 7,
	BVIBRATR_DEPTH_SUSTAIN		= 8,
	BVIBRATR_DEPTH_RELEASE		= 9,
	BVIBRATR_OSC1_FREQ			= 10,
	BVIBRATR_OSC1_MODE			= 11,
	BVIBRATR_OSC1_WAVEFORM		= 12,
	BVIBRATR_OSC2_AMP			= 13,
	BVIBRATR_OSC2_FREQ			= 14,
	BVIBRATR_OSC2_MODE			= 15,
	BVIBRATR_OSC2_WAVEFORM		= 16,
	BVIBRATR_OSC3_AMP			= 17,
	BVIBRATR_OSC3_FREQ			= 18,
	BVIBRATR_OSC3_MODE			= 19,
	BVIBRATR_OSC3_WAVEFORM		= 20,
	BVIBRATR_TREMOLO			= 21,
	BVIBRATR_NR_CONTROLLERS		= 22,

	BVIBRATR_LATENCY			= 22	// Output controller!
};

enum BVibratrOscModes
{
	BVIBRATR_OSC_MODE_PASS		= 1,
	BVIBRATR_OSC_MODE_LFO		= 1,
	BVIBRATR_OSC_MODE_ADD		= 2,
	BVIBRATR_OSC_MODE_USER		= 2,
	BVIBRATR_OSC_MODE_FM1		= 3,
	BVIBRATR_OSC_MODE_PM1		= 4,
	BVIBRATR_OSC_MODE_AM1		= 5,
	BVIBRATR_OSC_MODE_FM2		= 6,
	BVIBRATR_OSC_MODE_PM2		= 7,
	BVIBRATR_OSC_MODE_AM2		= 8
};

#endif /* PORTS_HPP_ */